/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jclec_problem_classification_dgc_DGCEvaluatorGPU */

#ifndef _Included_net_sf_jclec_problem_classification_dgc_DGCEvaluatorGPU
#define _Included_net_sf_jclec_problem_classification_dgc_DGCEvaluatorGPU
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sf_jclec_problem_classification_dgc_DGCEvaluatorGPU_serialVersionUID
#define net_sf_jclec_problem_classification_dgc_DGCEvaluatorGPU_serialVersionUID 6980709786864047100LL
#undef net_sf_jclec_problem_classification_dgc_DGCEvaluatorGPU_serialVersionUID
#define net_sf_jclec_problem_classification_dgc_DGCEvaluatorGPU_serialVersionUID 3613350191235561000LL
/*
 * Class:     net_sf_jclec_problem_classification_dgc_DGCEvaluatorGPU
 * Method:    nativeMalloc
 * Signature: (IIIIILnet/sf/jclec/problem/classification/dgc/DGCEvaluatorGPU;)V
 */
JNIEXPORT void JNICALL Java_net_sf_jclec_problem_classification_dgc_DGCEvaluatorGPU_nativeMalloc
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     net_sf_jclec_problem_classification_dgc_DGCEvaluatorGPU
 * Method:    nativeEvaluate
 * Signature: (ILnet/sf/jclec/problem/classification/dgc/DGCEvaluatorGPU;)V
 */
JNIEXPORT void JNICALL Java_net_sf_jclec_problem_classification_dgc_DGCEvaluatorGPU_nativeEvaluate
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_sf_jclec_problem_classification_dgc_DGCEvaluatorGPU
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_jclec_problem_classification_dgc_DGCEvaluatorGPU_nativeFree
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
